modules/Platforms/routes/web.php
<?php

Route::group(['middleware' => ['web', 'auth'], 'namespace' => 'Modules\Platforms\Http\Controllers'], function () {
    Route::get('/platform/create', 'PlatformsController@create')->name('user.platforms.store');
    Route::post('/platform/create', 'PlatformsController@store');

    Route::get('/platforms', 'PlatformsController@index')->name('user.platforms');
    Route::post('/platforms', 'PlatformsController@show');

    Route::group(['prefix' => '/offers', 'as' => 'offers.'], function () {
        Route::get('/', 'OfferController@index')->name('index');
        Route::get('/{offer}', 'OfferController@show')->name('show');
        Route::post('/', 'OfferController@search')->name('search');
    });

    Route::get('/statistics', 'StatisticsController@index')->name('statistics');
    Route::get('/statistics/video', 'StatisticsController@getVideoStatistics')->name('statistics.video');

    Route::get('/streams', 'StreamController@index')->name('streams');
    Route::get('/stream/{id}/delete', 'StreamController@destroy')->name('stream.delete');

    Route::get('/stream/{id}/stream', 'StreamController@create')->name('stream.create');
    Route::post('/stream/{id}/stream', 'StreamController@store');

    Route::get('/stream/{id}/edit', 'StreamController@edit')->name('stream.edit');
    Route::post('/stream/{id}/edit', 'StreamController@update');

    Route::post('/stream/create', 'StreamController@store');

    Route::resource('news', 'NewsController', [
        'only' => ['index', 'show']
    ])->parameters([
        'news' => 'article'
    ]);
});

Route::group(['namespace' => 'Modules\Platforms\Http\Controllers'], function () {
    Route::get('/link/{hash}/{subid?}', 'TrafficController@redirectUser')->name('redirectUser');


    Route::any('/postback/{system}', 'PostbackController@getPostback')->name('postback');
});

modules/Platforms/Entities/Stream.php
<?php

namespace Modules\Platforms\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Modules\Users\Entities\User;

class Stream extends Model
{

    use SoftDeletes;
    /**
     * @var array
     */
    protected $fillable = [
        'offer_id',
        'user_id',
        'landing_id',
        'title',
        'url',
        'hash'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function offer()
    {
        return $this->belongsTo(Offer::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function landing()
    {
        return $this->belongsTo(Landing::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function subids()
    {
        return $this->hasMany(Subid::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function events()
    {
        return $this->hasMany(Event::class);
    }
}

modules/Platforms/Http/Controllers/StreamController.php
<?php

namespace Modules\Platforms\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Platforms\Entities\Offer;
use Modules\Platforms\Entities\Stream;
use Psy\Util\Str;

class StreamController extends Controller
{

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $streams = \Auth::user()->streams()->orderByDesc('created_at')->get();

        return view('platforms::streams.index', compact('streams'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create($id)
    {
        $offer  = Offer::find($id);
        $stream = Stream::make();

        return view('platforms::streams.create', compact('offer', 'stream'));
    }

    public function store($id, Request $request)
    {
        $offer = Offer::find($id);

        $validator = \Validator::make($request->all(), [
            'title' => 'required|max:64',
        ], [
            'required' => 'Поле :attribute обязательно',
        ], [
            'title' => 'Название',
        ]);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        }

        $default_landing = $offer->landings()->first();

        $hash = null;

        while (! $hash) {
            $tmp = uniqid();

            $streams = Stream::where('hash', $tmp)->first();
            if (! $streams) {
                $hash = $tmp;
            }
        }

        $stream = Stream::create([
            'offer_id'   => $offer->id,
            'user_id'    => \Auth::id(),
            'landing_id' => $request->get('landing_id', $default_landing ? $default_landing->id : null),
            'title'      => $request->get('title'),
            'url'        => $request->get('url'),
            'hash'       => $hash,
        ]);

        $subids = explode(':', $request->get('subids'));

        foreach ($subids as $subid) {
            $stream->subids()->create([
                'name' => $subid
            ]);
        }

        return redirect(route('streams'));
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $stream = Stream::find($id);
        $offer  = $stream->offer;

        return view('platforms::streams.create', compact('offer', 'stream'));
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function update($id, Request $request)
    {
        $stream = Stream::find($id);

        $stream->update($request->except('subids'));

        $subids = explode(':', $request->get('subids'));

        $stream->subids()->delete();

        foreach ($subids as $subid) {
            $stream->subids()->create([
                'name' => $subid
            ]);
        }

        return redirect(route('streams'));
    }

    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $stream = Stream::where('id', $id)->where('user_id', \Auth::id())->firstOrFail();
        $stream->delete();

        return redirect()->back();
    }
}

modules/Platforms/resources/views/streams/create.blade.php
@extends('layouts.master')

@section('content')
    <section class="page-content creating-stream page-responsive">
        <div class="container">
            <div class="page-head">
                <div class="page-head__name">
                    <h1>{{ $stream->id ? 'Редактирование потока' : 'Создание потока' }}</h1>
                    <nav aria-label="breadcrumb" role="navigation">
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ url('/') }}">Главная</a></li>
                            <li class="breadcrumb-item active" aria-current="page">
                                <a>Создание потока</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="creating-stream">
                <form method="post">
                    {{ csrf_field() }}
                    <div class="card-bg">
                        <div class="form-group">
                            <label for="exampleInput">Оффер</label>
                            <p>{{ $offer->name }}</p>
                        </div>
                        <div class="form-group">
                            <label for="exampleInput">Название</label>
                            <input type="text" class="form-control" id="exampleInput" name="title"
                                   placeholder="Поток 71" value="{{ old('title', $stream->title) }}" required>
                        </div>
                    </div>

                    @if($offer->landings->count() > 1)
                        <h2>Выбор лендинга</h2>
                        <div class="company-table">
                            <div class="card">
                                <div class="card-header">
                                    <div class="row">
                                        <div class="col-4">
                                            <p>название</p>
                                        </div>
                                        <div class="col-8">
                                            <p>Ссылка</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-body card-playgrounds">
                                    @foreach($offer->landings as $landing)
                                        <div class="row">
                                            <div class="form-check">
                                                @if($stream->landing_id === $landing->id)
                                                    <input class="form-check-input" type="radio" name="landing_id" checked
                                                           id="gridRadios{{ $landing->id }}" value="{{ $landing->id }}">
                                                @else
                                                    <input class="form-check-input" type="radio" name="landing_id"
                                                           id="gridRadios{{ $landing->id }}" value="{{ $landing->id }}">
                                                @endif
                                            </div>
                                            <div class="col-4">
                                                <label for="gridRadios{{ $landing->id }}"><span>{{ $landing->name }}</span>
                                                    {{--<img data-toggle="tooltip" data-placement="top"--}}
                                                    {{--title="bars" src="{{ asset('/img/adaptive_icon.png') }}"--}}
                                                    {{--alt="">--}}
                                                </label>
                                            </div>
                                            <div class="col-8">
                                                <p>
                                                    <a href="{{ $landing->url }}"
                                                       target="_blank">{{ $landing->url }}</a>
                                                </p>
                                            </div>
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                        </div>
                    @endif

                    <h2>Дополнительные настройки</h2>
                    <div class="card-bg">
                        <div class="row">
                            <div class="col-md-6">
                                <label class="mr-sm-2" for="offisoff">Если оффер отключен</label>
                                <select class="custom-select mr-sm-2" id="offisoff">
                                    <option value="1" selected>One</option>
                                    <option value="2">Перевести по ссылке</option>
                                    <option value="3">Two</option>
                                    <option value="4">Three</option>
                                </select>
                            </div>
                            <div class="col-md-6 card-hide card-show">
                                <label class="mr-sm-2" for="23">Перевести по ссылке</label>
                                <input type="text" class="form-control" name="url" id="23"
                                       placeholder="https://www.youtube.com/">
                            </div>
                        </div>
                        <br>

                        <div class="row hidden">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="InputSubid">Subid</label>
                                    <input type="text" class="form-control" id="InputSubid" name="subids"
                                           placeholder="subid1:subid2:subid3:subid4"
                                           value="{{ $stream->subids->implode('name',':') }}">
                                </div>
                            </div>
                        </div>
                    </div>
                    <button class="btn btn-success button-submit">Создать поток</button>
                </form>
            </div>
        </div>
    </section>
@stop

modules/Platforms/resources/views/streams/index.blade.php
@extends('layouts.master')

@section('content')
    <section class="page-content flows page-responsive">
        <div class="container">
            <div class="page-head">
                <div class="page-head__name">
                    <h1>Потоки</h1>
                    <nav aria-label="breadcrumb" role="navigation">
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ url('/') }}">Главная</a></li>
                            <li class="breadcrumb-item active" aria-current="page">
                                <a href="{{ route('streams') }}">Потоки</a>
                            </li>
                        </ul>
                    </nav>
                </div>
                <div class="button-add">
                    {{--                    <a href="{{ route('stream.create') }}">+ Создать поток</a>--}}
                </div>
            </div>
            <div class="responsive-table flows-table">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-2">
                                <p>ID</p>
                            </div>
                            <div class="col-2">
                                <p>Дата</p>
                            </div>
                            <div class="col-3">
                                <p>Название</p>
                            </div>
                            <div class="col-3">
                                <p>оффер</p>
                            </div>
                        </div>
                    </div>
                    <div class="card-body card-playgrounds">
                        @foreach($streams as $stream)
                            <div class="row">
                                <div class="card-body__lastcol">
                                    <ul>
                                        <li><a data-toggle="tooltip" data-placement="top" title="bars"
                                               href="{{ route('stream.edit', ['id' => $stream]) }}"><i
                                                        class="fa fa-cog" aria-hidden="true"></i></a></li>
                                        <li><a data-toggle="tooltip" data-placement="top" title="bars" href="#"><i
                                                        class="fa fa-link" aria-hidden="true"></i></a></li>
                                        <li>
                                            <a data-toggle="tooltip" data-placement="top" title="bars"
                                               href="{{ route('stream.delete', ['id' => $stream->id]) }}">
                                                <i class="fa fa-times" aria-hidden="true"></i>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-2">
                                    <p>{{ $stream->hash }}</p>
                                </div>
                                <div class="col-2">
                                    <p>{{ $stream->created_at->format('d.m.Y') }}</p>
                                </div>
                                <div class="col-3">
                                    <p>{{ $stream->title }}</p>
                                </div>
                                <div class="col-3">
                                    <p>
                                        <a href="{{ route('offers.show', ['slug' => $stream->offer->slug]) }}">
                                            {{ $stream->offer->name }}
                                        </a>
                                    </p>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </section>
@stop