modules/Admin/routes/web.php
<?php

Route::group([
    'middleware' => ['web', 'admin'],
    'namespace'  => 'Modules\Admin\Http\Controllers',
    'prefix'     => 'admin',
    'as'         => 'admin.'
], function () {
    Route::get('/', 'AdminController@index')->name('admin');

    Route::resource('news', 'NewsController')->parameters([
        'news' => 'article'
    ]);

    Route::group(['prefix' => '/offers', 'as' => 'offers.'], function () {
        Route::get('/list', 'OfferController@index')->name('list');

        Route::delete('/delete/{id}', 'OfferController@destroy')->name('destroy');

        Route::get('/edit/{id}', 'OfferController@edit')->name('edit');
        Route::post('/edit/{id}', 'OfferController@update');

        Route::post('/landing/delete', 'OfferController@destroyLanding')->name('destroy.landing');
        Route::post('/rate/delete', 'OfferController@destroyRate')->name('destroy.rate');

        Route::get('/create', 'OfferController@create')->name('create');
        Route::post('/create', 'OfferController@store');

        Route::group(['prefix' => '/categories', 'as' => 'categories.'], function () {
            Route::get('/', 'CategoryController@index')->name('index');

            Route::get('/{category}/edit', 'CategoryController@edit')->name('edit');
            Route::post('/{category}/edit', 'CategoryController@update');

            Route::get('/create', 'CategoryController@create')->name('create');
            Route::post('/create', 'CategoryController@store');

            Route::delete('/{category}', 'CategoryController@destroy')->name('destroy');
        });
    });

    Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/', 'UserController@index')->name('index');
        Route::get('/{user}/edit', 'UserController@edit')->name('edit');
        Route::post('/{user}/edit', 'UserController@update');
        Route::delete('/{user}', 'UserController@destroy')->name('destroy');

        Route::get('/platform/confirm/{platform}', 'UserController@confirmPlatform')->name('platform.confirm');
        Route::get('/platform/delete/{platform}', 'UserController@destroyPlatform')->name('platform.destroy');

        Route::get('/platforms', 'UserController@getPlatforms')->name('platforms');
        Route::post('/platforms', 'UserController@storePlatform');

        Route::get('/statistics', 'UserController@getStatistics')->name('statistics');
    });

    Route::group(['prefix' => 'tickets', 'as' => 'tickets.'], function () {
        Route::get('/', 'TicketController@index')->name('index');
        Route::get('/create', 'TicketController@create')->name('create');
        Route::post('/create', 'TicketController@store')->name('store');

        Route::get('/chat', 'TicketController@chat')->name('chat');
        Route::post('/chat', 'TicketController@storeChat');
    });

    Route::group(['prefix' => 'creatives', 'as' => 'creatives.'], function () {
        Route::get('/{creative}/edit', 'CreativeController@edit')->name('edit');
        Route::post('/{creative}/edit', 'CreativeController@update');

        Route::get('/create/{offer}', 'CreativeController@create')->name('create');
        Route::post('/create/{offer}', 'CreativeController@store');

        Route::get('/{creative}/delete', 'CreativeController@destroy')->name('destroy');

        Route::post('/remove-upload', 'CreativeController@removeUpload')->name('removeUpload');
    });

    Route::group(['prefix' => 'countries', 'as' => 'countries.'], function () {
        Route::get('/', 'CountryController@index')->name('index');

        Route::get('/create', 'CountryController@create')->name('create');
        Route::post('/create', 'CountryController@store');

        Route::get('/{country}/edit', 'CountryController@edit')->name('edit');
        Route::post('/{country}/edit', 'CountryController@update');

        Route::get('/{country}/delete', 'CountryController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'campaigns', 'as' => 'campaigns.'], function () {
        Route::get('/', 'CampaignController@index')->name('index');

        Route::get('/{campaign}/edit', 'CampaignController@edit')->name('edit');
        Route::post('/{campaign}/edit', 'CampaignController@update');

        Route::get('/create', 'CampaignController@create')->name('create');
        Route::post('/create', 'CampaignController@store');

        Route::get('/{campaign}/delete', 'CampaignController@destroy')->name('destroy');
    });

    Route::group(['prefix' => '/wallets', 'as' => 'wallets.'], function () {
        Route::get('/', 'WalletController@index')->name('index');
    });
});

modules/Admin/Http/Controllers/CampaignController.php
<?php

namespace Modules\Admin\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Modules\Admin\Http\Requests\Campaigns\StoreCampaignRequest;
use Modules\Admin\Http\Requests\Campaigns\UpdateCampaignRequest;
use Modules\Campaigns\Entities\Campaign;

class CampaignController extends Controller
{

    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        $campaigns = Campaign::all();
        return view('admin::campaigns.index', compact('campaigns'));
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create(Campaign $campaign)
    {
        return view('admin::campaigns.edit', compact('campaign'));
    }

    /**
     * Store a newly created resource in storage.
     * @param StoreCampaignRequest $request
     * @return Response
     */
    public function store(StoreCampaignRequest $request)
    {
        $campaign = Campaign::make($request->all());

        $image = $request->file('image');

        $campaign->image = $image->storeAs('public/campaigns', uniqid().'.'.$image->getClientOriginalExtension());

        $campaign->available_budget = $campaign->budget;

        $status = $campaign->save();

        return back()->with('success', $status);
    }

    /**
     * Show the specified resource.
     * @return Response
     */
    public function show()
    {
        dd(1);
        return view('admin::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @return Response
     */
    public function edit(Campaign $campaign)
    {
        return view('admin::campaigns.edit', compact('campaign'));
    }

    /**
     * Update the specified resource in storage.
     * @param UpdateCampaignRequest $request
     * @return Response
     */
    public function update(UpdateCampaignRequest $request, Campaign $campaign)
    {
        if ($request->has('image')) {
            $image = $request->file('image');

            \Storage::delete($campaign->image);

            $campaign->image = $image->storeAs('public/campaigns', uniqid().'.'.$image->getClientOriginalExtension());

            $campaign->save();
        }

        $status = $campaign->update($request->except('image'));

        return back()->with('success', $status);
    }

    /**
     * Remove the specified resource from storage.
     * @return Response
     */
    public function destroy(Campaign $campaign)
    {
        \Storage::delete($campaign->image);

        $status = $campaign->delete();

        return response()->json(['success' => $status], 200);
    }
}

modules/Admin/resources/views/campaigns/_list.blade.php
@foreach($campaigns as $campaign)
    <tr>
        <td>{{ $campaign->id }}</td>
        <td><a href="{{ route('admin.campaigns.edit', ['slug' => $campaign->slug]) }}">{{ $campaign->name }}</a></td>
        <td>{{ $campaign->views }}</td>
        <td>{{ $campaign->available_budget }}</td>
        <td>{{ $campaign->price }}</td>
        <td>{{ $campaign->active ? 'активен' : 'не активен' }}</td>
        <td>{{ $campaign->order }}</td>
        <td>
            <a href="{{ route('admin.campaigns.edit', ['slug' => $campaign->slug]) }}"
               class="btn btn-info btn-sm">Редактировать</a>
            <a href="{{ route('admin.campaigns.destroy', ['slug' => $campaign->slug]) }}"
               class="btn btn-danger btn-sm btn-delete">Удалить</a>
        </td>
    </tr>
@endforeach

modules/Admin/resources/views/campaigns/edit.blade.php
@extends('admin::layouts.master')

@section('title', 'Campaigns')

@section('content')
    <div id="main" role="main">

        <!-- RIBBON -->
        <div id="ribbon">

            <!-- breadcrumb -->
            <ol class="breadcrumb">
                <li>Главная</li>
                <li>{{ $campaign->id ? 'Редактирование' : 'Добавление' }} видео кампании</li>
            </ol>

        </div>
        <!-- END RIBBON -->

        <!-- #MAIN CONTENT -->

        <!-- col -->
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <h1 class="page-title txt-color-blueDark">

                <!-- PAGE HEADER -->
                <i class="fa-fw fa fa-plus"></i>
                {{ $campaign->id ? 'Редактирование' : 'Добавление' }} видео кампании
            </h1>
        </div>
        <!-- end col -->

        <div class="col-sm-12 col-md-12 col-lg-12 sortable-grid ui-sortable">

            @if(session('success', false))
                <div class="alert alert-block alert-success">
                    <a class="close" data-dismiss="alert" href="#">×</a>
                    <h4 class="alert-heading"><i class="fa fa-check-square-o"></i> Check validation!</h4>
                    <p>
                        You may also check the form validation by clicking on the form action button. Please try and see the results below!
                    </p>
                </div>
            @endif

            <div class="jarviswidget well" >


                <div role="content">


                    <!-- widget content -->
                    <div class="widget-body">

                        <form method="POST" class="form-horizontal" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            <fieldset>
                                <legend>Введите основные данные</legend>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">Название кампании</label>
                                    <div class="col-md-10">
                                        <input value="{{ old('name') ?? $campaign->name }}" name="name" class="form-control" placeholder="Название кампании" type="text">
                                        @if ($errors->has('name'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('name') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-2 control-label" for="select-1">Кол-во просмотров</label>
                                    <div class="col-md-4">
                                        <input value="{{ old('views') ?? $campaign->views }}" name="views" class="form-control" placeholder="Сколько нужно просмотров рекламодателю" type="number">
                                        @if ($errors->has('views'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('views') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-2 control-label">Ссылка на видео</label>
                                    <div class="col-md-10">
                                        <input value="{{ old('video') ?? $campaign->video }}" name="video" class="form-control" placeholder="URL" type="text">
                                        @if ($errors->has('video'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('video') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-2 control-label">Описание</label>
                                    <div class="col-md-10">
                                        <textarea name="desc" class="form-control" placeholder="" rows="4">{{ old('desc') ?? $campaign->desc }}</textarea>
                                        @if ($errors->has('desc'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('desc') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-2 control-label">Правила</label>
                                    <div class="col-md-10">
                                        <textarea class="form-control" placeholder="Необязательно" rows="4"></textarea>
                                        @if ($errors->has('name'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('name') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-2 control-label">Социальная сеть</label>
                                    <div class="col-md-10">
                                        <select class="form-control" id="select-1">
                                            <option>Выберите соц. сеть</option>
                                            <option>VK</option>
                                            <option>YouTube</option>
                                            <option>Одноклассники</option>
                                        </select>
                                        @if ($errors->has('name'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('name') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-2 control-label">Бюджет</label>
                                    <div class="col-md-4">
                                        <div class="input-group">
                                            <span class="input-group-addon">Доступный бюджет :</span>
                                            <input value="{{ old('budget') ?? $campaign->budget }}" name="budget" class="form-control" type="text">
                                            <span class="input-group-addon">руб.</span>
                                        </div>
                                        @if ($errors->has('budget'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('budget') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-2 control-label">Цена</label>
                                    <div class="col-md-4">
                                        <div class="input-group">
                                            <span class="input-group-addon">Цена за один просмотр :</span>
                                            <input value="{{ old('price') ?? $campaign->price }}" name="price" class="form-control" type="text">
                                            <span class="input-group-addon">руб.</span>
                                        </div>
                                        @if ($errors->has('price'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('price') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>


                            </fieldset>

                            <fieldset>
                                <legend>Материалы</legend>

                                <div class="form-group">
                                    <label class="col-md-2 control-label">Постер</label>
                                    <div class="col-md-10">
                                        <input name="image" id="exampleInputFile1" type="file" class="btn btn-primary">
                                        @if ($errors->has('image'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('image') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                            </fieldset>

                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-12">
                                        <button class="btn btn-primary" type="submit">
                                            <i class="fa fa-save"></i>
                                            Сохранить
                                        </button>
                                    </div>
                                </div>
                            </div>

                        </form>

                    </div>
                    <!-- end widget content -->

                </div>


            </div>

        </div>

        <!-- end row -->

        <!-- END #MAIN CONTENT -->

    </div>
@stop

modules/Admin/resources/views/campaigns/index.blade.php
@extends('admin::layouts.master')

@section('title', 'Campaigns list')

@section('content')
    <div id="main" role="main">

        <!-- RIBBON -->
        <div id="ribbon">

            <!-- breadcrumb -->
            <ol class="breadcrumb">
                <li>Главная</li>
                <li>Видео кампании</li>
            </ol>

        </div>
        <!-- END RIBBON -->

        <!-- #MAIN CONTENT -->

        <!-- col -->
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <h1 class="page-title txt-color-blueDark">

                <!-- PAGE HEADER -->
                <i class="fa-fw fa fa-ticket"></i>
                Видео кампании
            </h1>
        </div>
        <!-- end col -->

        <div class="col-sm-12 col-md-12 col-lg-12 sortable-grid ui-sortable">

            <div class="jarviswidget well" >

                <div role="content">

                    <!-- widget content -->
                    <div class="widget-body">

                        <legend></legend>

                        <table id="myTable">
                            <thead>
                            <tr>
                                <th>№</th>
                                <th>Название кампании</th>
                                <th>Кол-во просмотров</th>
                                <th>Доступный бюджет</th>
                                <th>Цена за один просмотр</th>
                                <th>Статус</th>
                                <th>Приоритет</th>
                                <th>Операции</th>
                            </tr>
                            </thead>
                            <tbody>
                                @include('admin::campaigns._list')
                            </tbody>
                        </table>

                    </div>
                    <!-- end widget content -->

                </div>

            </div>

        </div>

        <!-- end row -->

        <!-- END #MAIN CONTENT -->

    </div>

    @push('js')
        <script type="text/javascript">
            $(function(){
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });

                $('.btn-delete').click(function (e) {
                    e.preventDefault();
                    $.ajax({
                        type: "GET",
                        url: $(this).attr('href'),
                        success: function (response) {
                            $(e.target).parent().parent().remove()
                        }
                    });
                });

                $('#myTable').DataTable({
                    "processing": true,
                    "responsive": true,
                    "language": {
                        "lengthMenu": "Показывать _MENU_ записей на странице",
                        "zeroRecords": "Записей не найдено",
                        "loadingRecords": "Загрузка... может занять несколько секунд...",
                        "info": "Страница _PAGE_ из _PAGES_",
                        "infoEmpty": "Показано с 0 по 0 из 0 записей",
                        "search": "Фильтр",
                        "infoFiltered": "(Найдено записей: _TOTAL_)",
                        "sInfo": "Показано с _START_ по _END_ из _TOTAL_ записей",
                        "paginate":
                            {
                                "first":      "Первая",
                                "last":       "Последняя",
                                "next":       "Следующая",
                                "previous":   "Предыдущая"
                            }
                    },
                    "aaSorting": [[0, "desc"]],
                    "iDisplayLength": 10
                });
            });
        </script>
    @endpush
@stop