modules/Campaigns/routes/web.php
<?php

Route::group(['middleware' => ['web', 'auth'], 'namespace' => 'Modules\Campaigns\Http\Controllers'], function()
{
    Route::group(['prefix' => '/campaigns', 'as' => 'campaigns.'], function () {
        Route::get('/', 'CampaignsController@index')->name('index');
        Route::post('/', 'CampaignsController@search');
        Route::get('/{campaign}', 'CampaignsController@show')->name('show');
    });
});

modules/Campaigns/Entities/Campaign.php
<?php

namespace Modules\Campaigns\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Query\Builder;

class Campaign extends Model
{

    protected $fillable = [
        'name',
        'slug',
        'image',
        'budget',
        'available_budget',
        'price',
        'start_at',
        'video',
        'views',
        'desc'
    ];

    protected $dates = [
        'start_at'
    ];

    protected $appends = [
        'progress'
    ];

    /**
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function conditions()
    {
        return $this->belongsToMany(Condition::class);
    }


    /**
     * @param Builder $builder
     */
    public function scopeSorted($builder)
    {
        $builder->where('active', true)->orderBy('order');
    }

    /**
     * @return float|int
     */
    public function getProgressAttribute()
    {
        if ($this->budget === 0) {
            return 0;
        }
        return 100 - round($this->available_budget * 100 / $this->budget, 2);
    }

    /**
     * @return string
     */
    public function getImageUrlAttribute()
    {
        return \Storage::url($this->image);
    }
}

modules/Campaigns/Entities/Condition.php
<?php

namespace Modules\Campaigns\Entities;

use Illuminate\Database\Eloquent\Model;

class Condition extends Model
{
    protected $fillable = [
        'name', 'label'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function campaigns()
    {
        return $this->belongsToMany(Campaign::class);
    }
}

modules/Campaigns/Http/Controllers/CampaignsController.php
<?php

namespace Modules\Campaigns\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Modules\Campaigns\Entities\Campaign;
use Modules\Users\Entities\User;

class CampaignsController extends Controller
{

    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        $campaigns = Campaign::sorted()->get();

        return view('campaigns::index', compact('campaigns'));
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        return view('campaigns::create');
    }

    /**
     * Store a newly created resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function store(Request $request)
    {
    }

    /**
     * Show the specified resource.
     *
     * @param Campaign $campaign
     *
     * @return Response
     */
    public function show(Campaign $campaign)
    {
        $user = auth()->user();

        $platforms = $user->platforms()->where('price', '<=', $campaign->price)->get();

        $campaign->loadMissing('conditions');

        return view('campaigns::show', compact('campaign', 'platforms'));
    }

    /**
     * Show the form for editing the specified resource.
     * @return Response
     */
    public function edit()
    {
        return view('campaigns::edit');
    }

    /**
     * Update the specified resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function update(Request $request)
    {
    }

    /**
     * Remove the specified resource from storage.
     * @return Response
     */
    public function destroy()
    {
    }

    public function search(Request $request)
    {
        if ($request->has('search', false)) {
            $campaigns = Campaign::where('name', 'like', '%'.$request->search.'%')
                ->orWhere('available_budget', 'like', '%'.$request->search.'%')
                ->orWhere('price', 'like', '%'.$request->search.'%')
                ->get();
        } else {
            $campaigns = Campaign::sorted()->get();
        }

        return view('campaigns::campaign_list', compact('campaigns'));
    }
}

modules/Campaigns/resources/views/campaign_list.blade.php
@foreach($campaigns as $campaign)
    <div class="col-md-4 col-sm-6">
        <div class="companies-col">
            <img src="{{ asset($campaign->imageUrl) }}" alt="">
            <div class="companies-col__content">
                <h3 class="companies-col__title">{{ $campaign->name }}</h3>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
                        {{ $campaign->progress }}%
                    </div>
                </div>
                <div class="companies-col__info">
                    <p><span>Стоимость просмотра:</span><b>до {{ $campaign->price }} RUB</b></p>
                    <p><span>Доступный бюджет:</span><b>{{ $campaign->available_budget }} RUB</b></p>
                    <p><span>Доступно:</span><b>2 площадки</b></p>
                    <p><span>Дата старта:</span><b>{{ $campaign->start_at->format('d.m.Y, h:m') }}</b></p>
                </div>
                <a href="{{ route('campaigns.show', ['slug' => $campaign->slug]) }}" class="companies-btn btn btn-outline-secondary">Разместить</a>
            </div>
        </div>
    </div>
@endforeach

modules/Campaigns/resources/views/index.blade.php
@extends('layouts.master')

@section('content')
    <section class="page-content listCompanies">
        <div class="container">
            <div class="page-head">
                <div class="page-head__name">
                    <h1>Видео-кампании</h1>
                    <nav aria-label="breadcrumb" role="navigation">
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ url('/') }}">Главная</a></li>
                            <li class="breadcrumb-item active" aria-current="page"><a href="{{ route('campaigns.index') }}">Видео-кампании</a></li>
                        </ul>
                    </nav>
                </div>
                <div class="page-head__right">
                    <div class="icon-soc">
                        <a href="#"><i class="fa fa-vk" aria-hidden="true"></i></a>
                    </div>
                    <div class="drop">
                        <div>
                            <p>Характер</p>
                            <ul>
                                <li><a href="#"><img src="vendors/flags/1x1/hn.svg" alt=""></a></li>
                                <li><a href="#"><img src="vendors/flags/1x1/hn.svg" alt=""></a></li>
                                <li><a href="#"><img src="vendors/flags/1x1/hn.svg" alt=""></a></li>
                                <li><a href="#"><img src="vendors/flags/1x1/hn.svg" alt=""></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="search-input">
                        <input type="text" placeholder="Поиск">
                        <i class="fa fa-search" aria-hidden="true"></i>
                    </div>
                </div>
            </div>
            <div class="row campaigns-list">
                @include('campaigns::campaign_list')
            </div>
        </div>
    </section>

    <script>
        window.onload = function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $('.search-input input').on('input', function () {
                $.ajax({
                    type: "POST",
                    data: {
                        search: $(this).val()
                    },
                    success: function (response) {
                        $('.campaigns-list').html(response)
                    },
                });
            })
        }
    </script>
@stop

modules/Campaigns/resources/views/platform_list.blade.php
@foreach($platforms as $platform)
    <div class="row">
        <div class="form-check">
            <input class="form-check-input" type="checkbox" id="blankCheckbox" value="option1" aria-label="...">
        </div>
        <div class="col-4">
            <div class="card-col__row">
                <div class="card-col__img">
                    <img src="{{ asset('img/human-small.png') }}" alt="">
                </div>
                <div>
                    <p>{{ $platform->name }}</p>
                </div>
            </div>
        </div>
        <div class="col-2">
            <p>{{ $platform->price }} RUB</p>
        </div>
        <div class="col-4">
            <p>Не размещена</p>
        </div>
        <div class="col-2">
            <span class="btn-plus">+</span>
        </div>
    </div>
@endforeach

modules/Campaigns/resources/views/show.blade.php
@extends('layouts.master')

@section('content')
    <section class="page-content company">
        <div class="container">
            <div class="page-head">
                <div class="page-head__name">
                    <h1>Просмотр кампании</h1>
                    <nav aria-label="breadcrumb" role="navigation">
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ url('/') }}">Главная</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('campaigns.index') }}">Видео-кампании</a></li>
                            <li class="breadcrumb-item active" aria-current="page">
                                <a href="{{ route('campaigns.show', ['slug' => $campaign->slug]) }}">Просмотр кампании</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="company-content">
                <div class="row">
                    <div class="col-md-7">
                        <img src="{{ asset($campaign->imageUrl) }}" alt="">
                    </div>
                    <div class="col-md-5">
                        <div class="companies-col__content">
                            <h3 class="companies-col__title">{{ $campaign->name }}</h3>
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
                                    {{ $campaign->progress }}%
                                </div>
                            </div>
                            <div class="companies-col__info">
                                <p><span>Стоимость просмотра:</span><b>до {{ $campaign->price }} RUB</b></p>
                                <p><span>Доступный бюджет:</span><b>{{ $campaign->available_budget }} RUB</b></p>
                                <p><span>Доступно:</span><b>{{ count($platforms) }} {{ trans_choice('campaigns::campaigns.platforms', count($platforms)) }}</b></p>
                                <p><span>Дата старта:</span><b>{{ $campaign->start_at->format('d.m.Y, h:m') }}</b></p>
                            </div>
                            <div class="companies-col__bottom">
                                <p>Условия размещения</p>
                                <ul>
                                    @foreach($campaign->conditions as $condition)
                                        <li>— {{ $condition->name }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="company-table">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-4">
                                <p>Площадка</p>
                            </div>
                            <div class="col-2">
                                <p>Стоимость</p>
                            </div>
                            <div class="col-4">
                                <p>последнее размещение</p>
                            </div>
                            <div class="col-2">
                                <p>таймер размещений</p>
                            </div>
                        </div>
                    </div>
                    <div class="card-body card-playgrounds">
                        @include('campaigns::platform_list')
                        <div class="card-playgrounds__btn">
                            <a class="btn btn-success" href="#">Разместить</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@stop