modules/Admin/routes/web.php
<?php

Route::group([
    'middleware' => ['web', 'admin'],
    'namespace'  => 'Modules\Admin\Http\Controllers',
    'prefix'     => 'admin',
    'as'         => 'admin.'
], function () {
    Route::get('/', 'AdminController@index')->name('admin');

    Route::resource('news', 'NewsController')->parameters([
        'news' => 'article'
    ]);

    Route::group(['prefix' => '/offers', 'as' => 'offers.'], function () {
        Route::get('/list', 'OfferController@index')->name('list');

        Route::delete('/delete/{id}', 'OfferController@destroy')->name('destroy');

        Route::get('/edit/{id}', 'OfferController@edit')->name('edit');
        Route::post('/edit/{id}', 'OfferController@update');

        Route::post('/landing/delete', 'OfferController@destroyLanding')->name('destroy.landing');
        Route::post('/rate/delete', 'OfferController@destroyRate')->name('destroy.rate');

        Route::get('/create', 'OfferController@create')->name('create');
        Route::post('/create', 'OfferController@store');

        Route::group(['prefix' => '/categories', 'as' => 'categories.'], function () {
            Route::get('/', 'CategoryController@index')->name('index');

            Route::get('/{category}/edit', 'CategoryController@edit')->name('edit');
            Route::post('/{category}/edit', 'CategoryController@update');

            Route::get('/create', 'CategoryController@create')->name('create');
            Route::post('/create', 'CategoryController@store');

            Route::delete('/{category}', 'CategoryController@destroy')->name('destroy');
        });
    });

    Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/', 'UserController@index')->name('index');
        Route::get('/{user}/edit', 'UserController@edit')->name('edit');
        Route::post('/{user}/edit', 'UserController@update');
        Route::delete('/{user}', 'UserController@destroy')->name('destroy');

        Route::get('/platform/confirm/{platform}', 'UserController@confirmPlatform')->name('platform.confirm');
        Route::get('/platform/delete/{platform}', 'UserController@destroyPlatform')->name('platform.destroy');

        Route::get('/platforms', 'UserController@getPlatforms')->name('platforms');
        Route::post('/platforms', 'UserController@storePlatform');

        Route::get('/statistics', 'UserController@getStatistics')->name('statistics');
    });

    Route::group(['prefix' => 'tickets', 'as' => 'tickets.'], function () {
        Route::get('/', 'TicketController@index')->name('index');
        Route::get('/create', 'TicketController@create')->name('create');
        Route::post('/create', 'TicketController@store')->name('store');

        Route::get('/chat', 'TicketController@chat')->name('chat');
        Route::post('/chat', 'TicketController@storeChat');
    });

    Route::group(['prefix' => 'creatives', 'as' => 'creatives.'], function () {
        Route::get('/{creative}/edit', 'CreativeController@edit')->name('edit');
        Route::post('/{creative}/edit', 'CreativeController@update');

        Route::get('/create/{offer}', 'CreativeController@create')->name('create');
        Route::post('/create/{offer}', 'CreativeController@store');

        Route::get('/{creative}/delete', 'CreativeController@destroy')->name('destroy');

        Route::post('/remove-upload', 'CreativeController@removeUpload')->name('removeUpload');
    });

    Route::group(['prefix' => 'countries', 'as' => 'countries.'], function () {
        Route::get('/', 'CountryController@index')->name('index');

        Route::get('/create', 'CountryController@create')->name('create');
        Route::post('/create', 'CountryController@store');

        Route::get('/{country}/edit', 'CountryController@edit')->name('edit');
        Route::post('/{country}/edit', 'CountryController@update');

        Route::get('/{country}/delete', 'CountryController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'campaigns', 'as' => 'campaigns.'], function () {
        Route::get('/', 'CampaignController@index')->name('index');

        Route::get('/{campaign}/edit', 'CampaignController@edit')->name('edit');
        Route::post('/{campaign}/edit', 'CampaignController@update');

        Route::get('/create', 'CampaignController@create')->name('create');
        Route::post('/create', 'CampaignController@store');

        Route::get('/{campaign}/delete', 'CampaignController@destroy')->name('destroy');
    });

    Route::group(['prefix' => '/wallets', 'as' => 'wallets.'], function () {
        Route::get('/', 'WalletController@index')->name('index');
    });
});

modules/Admin/Http/Controllers/NewsController.php
<?php

namespace Modules\Admin\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Storage;
use Modules\Admin\Http\Requests\Articles\ArticleStoreRequest;
use Modules\Admin\Http\Requests\Articles\ArticleUpdateRequest;
use Modules\Platforms\Entities\Article;

/**
 * Class NewsController
 * @package Modules\Admin\Http\Controllers
 */
class NewsController extends Controller
{

    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        $news = Article::latest()->paginate(10);

        return view('admin::news.index', compact('news'));
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create(Article $article)
    {
        return view('admin::news.create', compact('article'));
    }

    /**
     * Store a newly created resource in storage.
     * @param  ArticleStoreRequest $request
     * @return Response
     */
    public function store(ArticleStoreRequest $request)
    {
        $img = $request->file('image');

        $article = Article::make($request->except('image'));

        $article->image = $img->storeAs('public/images/news', uniqid().'.'.$img->getClientOriginalExtension());

        $article->save();

        return redirect()->route('admin.news.show', ['id' => $article->id]);
    }

    /**
     * Show the specified resource.
     * @param Article $article
     * @return Response
     */
    public function show(Article $article)
    {
        return view('admin::news.show', compact('article'));
    }

    /**
     * Show the form for editing the specified resource.
     * @return Response
     */
    public function edit(Article $article)
    {
        return view('admin::news.edit', compact('article'));
    }

    /**
     * Update the specified resource in storage.
     * @param  ArticleUpdateRequest $request
     * @param  Article $article
     * @return Response
     * @throws \Throwable
     */
    public function update(ArticleUpdateRequest $request, Article $article)
    {
        if ($request->has('image')) {
            $img = $request->file('image');

            Storage::delete($article->image);

            $imgName = uniqid().'.'.$img->getClientOriginalExtension();

            $article->image = $img->storeAs('public/images/news', $imgName);

            $article->save();
        }

        $article->update($request->except('image'));

        return redirect()->route('admin.news.show', ['id' => $article->id]);
    }

    /**
     * Remove the specified resource from storage.
     * @param Article $article
     * @return Response
     */
    public function destroy(Article $article)
    {
        Storage::delete($article->image);

        $status = $article->delete();

        return redirect()
            ->route('admin.news.index')
            ->with('success', $status);
    }
}

modules/Admin/resources/views/news/_form.blade.php
<div class="jarviswidget well">

    <div role="content">

        <div class="widget-body">

            <form class="form-horizontal" action="{{ $article->id ? route('admin.news.update', ['id' => $article->id]) : route('admin.news.store') }}" method="post" enctype="multipart/form-data">

                @if ($article->id)
                    @method('PUT')
                @else
                    @method('POST')
                @endif

                @csrf

                <fieldset>
                    <legend>Введите основные данные</legend>

                    <div class="form-group">
                        <label class="col-md-2 control-label ">Заголовок</label>
                        <div class="col-md-10">
                            <input value="{{ old('name') ?? $article->name }}" class="form-control" placeholder="Название новости" type="text" name="name">
                            @if ($errors->has('name'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-2 control-label">Новость</label>
                        <div class="col-md-10">
                            <textarea class="form-control" id="text-editor" placeholder="" name="text"
                                      rows="4">{{ old('text') ?? $article->text }}</textarea>
                            @if ($errors->has('text'))
                                <span class="help-block">
                                <strong>{{ $errors->first('text') }}</strong>
                            </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-2 control-label"></label>
                        <div class="col-md-10">
                            @if ($article->id)
                                <img src="{{ asset($article->imageUrl) }}" />
                            @endif
                            <input id="exampleInputFile1" type="file" name="image">
                            @if ($errors->has('image'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('image') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                </fieldset>

                <div class="form-actions">
                    <div class="row">
                        <div class="col-md-12">
                            <button class="btn btn-primary" type="submit">
                                <i class="fa fa-save"></i>
                                Сохранить
                            </button>
                        </div>
                    </div>
                </div>

            </form>

        </div>

    </div>

</div>

<script>
    window.onload = function () {
        if ($('#text-editor').length)
            CKEDITOR.replace('text-editor');
    }
</script>

modules/Admin/resources/views/news/create.blade.php
@extends('admin::layouts.master')

@section('title', 'Создание новости')

@section('content')
    <div id="main" role="main">

        <!-- RIBBON -->
        <div id="ribbon">

            <!-- breadcrumb -->
            <ol class="breadcrumb">
                <li>Главная</li>
                <li>Создание новости</li>
            </ol>

        </div>
        <!-- END RIBBON -->

        <!-- #MAIN CONTENT -->

        <!-- col -->
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <h1 class="page-title txt-color-blueDark">

                <!-- PAGE HEADER -->
                <i class="fa-fw fa fa-rss"></i>
                Создание новости
            </h1>
        </div>
        <!-- end col -->

        <div class="col-sm-12 col-md-12 col-lg-12 sortable-grid ui-sortable">

            <!--<div class="alert alert-block alert-success">
                <a class="close" data-dismiss="alert" href="#">×</a>
                <h4 class="alert-heading"><i class="fa fa-check-square-o"></i> Check validation!</h4>
                <p>
                    You may also check the form validation by clicking on the form action button. Please try and see the results below!
                </p>
            </div>-->

            @include('admin::news._form', ['article' => $article])

        </div>

        <!-- end row -->

        <!-- END #MAIN CONTENT -->

    </div>
@stop

modules/Admin/resources/views/news/edit.blade.php
@extends('admin::layouts.master')

@section('title', 'Редактирование новости ' . $article->name)

@section('content')
    <div id="main" role="main">

        <!-- RIBBON -->
        <div id="ribbon">

            <!-- breadcrumb -->
            <ol class="breadcrumb">
                <li>Главная</li>
                <li>Создание новости</li>
            </ol>

        </div>
        <!-- END RIBBON -->

        <!-- #MAIN CONTENT -->

        <!-- col -->
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <h1 class="page-title txt-color-blueDark">

                <!-- PAGE HEADER -->
                <i class="fa-fw fa fa-rss"></i>
                Создание новости
            </h1>
        </div>
        <!-- end col -->

        <div class="col-sm-12 col-md-12 col-lg-12 sortable-grid ui-sortable">

            <!--<div class="alert alert-block alert-success">
                <a class="close" data-dismiss="alert" href="#">×</a>
                <h4 class="alert-heading"><i class="fa fa-check-square-o"></i> Check validation!</h4>
                <p>
                    You may also check the form validation by clicking on the form action button. Please try and see the results below!
                </p>
            </div>-->

            @include('admin::news._form', ['article' => $article])

        </div>

        <!-- end row -->

        <!-- END #MAIN CONTENT -->

    </div>
@stop

modules/Admin/resources/views/news/index.blade.php
@extends('admin::layouts.master')

@section('title', 'Список новостей')

@section('content')
    <div id="main" role="main">

        <!-- RIBBON -->
        <div id="ribbon">

            <!-- breadcrumb -->
            <ol class="breadcrumb">
                <li>Главная</li>
                <li>Список новостей</li>
            </ol>

        </div>
        <!-- END RIBBON -->

        <!-- #MAIN CONTENT -->

        <!-- col -->
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <h1 class="page-title txt-color-blueDark">

                <!-- PAGE HEADER -->
                <i class="fa-fw fa fa-rss"></i>
                Список новостей
            </h1>
        </div>
        <!-- end col -->

        <div class="col-sm-12 col-md-12 col-lg-12 sortable-grid ui-sortable">
            <div class="jarviswidget well">
                <div role="content">
                    <div class="widget-body">
                        <div id="myTable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="dataTables_length" id="myTable_length">
                                        <label>Показывать
                                            <select name="myTable_length" aria-controls="myTable" class="form-control input-sm">
                                                <option value="10">10</option>
                                                <option value="25">25</option>
                                                <option value="50">50</option>
                                                <option value="100">100</option>
                                            </select>
                                            записей на странице</label>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div id="myTable_filter" class="dataTables_filter">
                                        <label>Фильтр
                                            <input type="search" class="form-control" placeholder="" aria-controls="myTable">
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <table id="myTable" class="dataTable no-footer" role="grid" aria-describedby="myTable_info">
                                        <thead>
                                        <tr role="row">
                                            <th class="sorting_desc" tabindex="0" aria-controls="myTable" rowspan="1" colspan="1" aria-sort="descending" aria-label="Дата: activate to sort column ascending" style="width: 287px;">Дата</th>
                                            <th class="sorting" tabindex="0" aria-controls="myTable" rowspan="1" colspan="1" aria-label="Название: activate to sort column ascending" style="width: 689px;">Название</th>
                                            <th class="sorting" tabindex="0" aria-controls="myTable" rowspan="1" colspan="1" aria-label="Операции: activate to sort column ascending" style="width: 332px;">Операции</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($news as $article)
                                            <tr role="row">
                                                <td class="sorting_1">{{ $article->created_at->format('d.m.Y H:i') }}</td>
                                                <td><a href="{{ route('admin.news.show', ['id' => $article->id]) }}">{{ $article->name }}</a></td>
                                                <td>
                                                    <a href=" {{ route('admin.news.edit', ['id' => $article->id]) }} " class="btn btn-info btn-sm">Ред.</a>
                                                    <form method="POST" action="{{ route('admin.news.destroy', ['id' => $article->id]) }}" style="display: inline">
                                                        @method('delete')
                                                        @csrf
                                                        <button class="btn btn-danger btn-sm">Удалить</button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                    <div id="myTable_processing" class="dataTables_processing panel panel-default" style="display: none;">Processing...</div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-sm-5">
                                    <div class="dataTables_info" id="myTable_info" role="status" aria-live="polite">Показано с {{ ($news->currentPage() - 1) * $news->perPage() + 1 }} по {{ $news->currentPage() * $news->perPage() }} из {{ $news->total() }} записей</div>
                                </div>
                                <div class="col-sm-7">
                                    <div class="pull-right">
                                        {{ $news->links() }}
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

            </div>

        </div>

        <!-- end row -->

        <!-- END #MAIN CONTENT -->

    </div>
@stop

modules/Admin/resources/views/news/show.blade.php
@extends('admin::layouts.master')

@section('title', $article->name)

@section('content')
    <div id="main" role="main">

        <!-- RIBBON -->
        <div id="ribbon">

            <!-- breadcrumb -->
            <ol class="breadcrumb">
                <li>Главная</li>
                <li>Просмотр новости</li>
            </ol>

        </div>
        <!-- END RIBBON -->

        <!-- #MAIN CONTENT -->

        <!-- col -->
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <h1 class="page-title txt-color-blueDark">

                <!-- PAGE HEADER -->
                <i class="fa-fw fa fa-rss"></i>
                Просмотр новости
            </h1>
        </div>
        <!-- end col -->

        <div class="col-sm-12 col-md-12 col-lg-12 sortable-grid ui-sortable">
            <div class="jarviswidget well">

                <div role="content">

                    <div class="widget-body">
                        <legend>{{ $article->name }}</legend>
                        <div class="row">
                            <div class="col-sm-2">

                                <div class="container-fluid">
                                    <img src="{{ asset($article->imageUrl) }}" width="100" height="100">
                                </div>

                            </div>

                            <div class="col-sm-10">

                                <div class="container-fluid">

                                    <p class="text-muted">{{ $article->created_at->format('d.m.Y H:i') }}</p>

                                    {!! $article->text !!}

                                </div>

                            </div>
                        </div>

                    </div>

                </div>

            </div>

        </div>

        <!-- end row -->

        <!-- END #MAIN CONTENT -->

    </div>
@stop